### PR TITLE
Branch1

### PR DESCRIPTION
**Pull request by GhodkiS**

### CODE REVIEW

**Comment by GhodkiS** [comment]
.lock app2-dev --reason "testing application-2 on dev"

**Comment by GhodkiS** [comment]
.lock app1-dev --details

**Comment by GhodkiS** [comment]
.lock --details

**Comment by GhodkiS** [comment]
.lock --reason "deploying f1 to production"

**Comment by shghodki** [comment]
.lock --details

**Comment by shghodki** [comment]
.deploy

**Comment by shghodki** [comment]
@GhodkiS is it ok to unlock?

**Comment by GhodkiS** [comment]
its okay go ahead.

**Comment by shghodki** [comment]
.unlock

**Comment by shghodki** [comment]
.deploy app1-dev

**Comment by shghodki** [comment]
.lock app1-dev --details

**Comment by shghodki** [comment]
.deploy app1-dev

**Comment by shghodki** [comment]
.deploy app1-dev

**Comment by shghodki** [comment]
.lock app1-dev --details

**Comment by shghodki** [comment]
.lock app1-dev --details

**Comment by shghodki** [comment]
.lock --details

**Comment by GhodkiS** [comment]
.lock app1-dev --details

**Comment by GhodkiS** [comment]
.deploy app1-dev

**Comment by GhodkiS** [comment]
.unlock app1-dev --reason "confirmed with shghodki"

**Comment by shghodki** [comment]
.deploy app1-dev

**Comment by shghodki** [comment]
.deploy app1-dev

**Comment by shghodki** [comment]
.lock app1-dev --details

**Comment by shghodki** [comment]
.deploy app1-dev

**Comment by shghodki** [comment]
.deploy app1-dev

**Comment by GhodkiS** [comment]
.deploy app1-dev

**Comment by GhodkiS** [comment]
.deploy app2-dev

**Comment by GhodkiS** [comment]
.deploy app2-dev

**Comment by GhodkiS** [comment]
.lock app2-dev --info

**Comment by GhodkiS** [comment]
.unlock app2-dev

**Pull request closed without merging**
